logsetup: close opened file descriptor (CRAFT-503)
Attempting to unlink the open file on Windows results in:

PermissionError: [WinError 32] The process cannot access the file because it is
being used by another process.

Save off the file handle and close it before unlinking.

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>