spread: disable reactive spread tests
Currenly failing:

:: Fatal Python error: init_sys_streams: can't initialize sys standard streams
:: Python runtime state: core initialized
:: Traceback (most recent call last):
::   File "/snap/charm/677/usr/lib/python3.10/io.py", line 54, in <module>
:: ImportError: cannot import name 'text_encoding' from 'io' (unknown location)
:: dpkg: error processing package python3-six (--configure):
::  installed python3-six package post-installation script subprocess returned error exit status 1
:: dpkg: dependency problems prevent configuration of virtualenv:
::  virtualenv depends on python3-virtualenv; however:
::   Package python3-virtualenv is not configured yet.
::
:: dpkg: error processing package virtualenv (--configure):
::  dependency problems - leaving unconfigured
:: Setting up git-man (1:2.25.1-1ubuntu3.5) ...
:: Setting up python-pip-whl (20.0.2-5ubuntu1.6) ...
:: Setting up python3-lib2to3 (3.8.10-0ubuntu1~20.04) ...
:: Setting up python3-appdirs (1.4.3-2.1) ...
:: Fatal Python error: init_sys_streams: can't initialize sys standard streams
:: Python runtime state: core initialized
:: Traceback (most recent call last):
::   File "/snap/charm/677/usr/lib/python3.10/io.py", line 54, in <module>
:: ImportError: cannot import name 'text_encoding' from 'io' (unknown location)
:: dpkg: error processing package python3-appdirs (--configure):
::  installed python3-appdirs package post-installation script subprocess returned error exit status 1

Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>