snap: add configure hook with support for provider (CRAFT-363)
- Add snap module to manage snap-configuration logic with tests.

- Update requirements to include snap-helpers.

- Add configure script entry point for snap to query and validate
  snap configuration.

- Enable (unused) configuration for 'provider', erroring if set to
  anything other than multipass or lxd.

Example error:
```
$ snap set charmcraft provider=invalid
error: cannot perform the following tasks:
- Run configure hook of "charmcraft" snap (run hook "configure":
  Invalid snap configuration: provider 'invalid' is not supported.)
```

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>