test: refactor init-extensions tests to avoid using ops.testing.Context.charm_spec (#2527)
The `ops.testing` framework currently exposes the private `_CharmSpec`
class via the `Context.charm_spec` attribute
(https://github.com/canonical/operator/issues/2131). Charm Tech will
deprecate this attribute soon
(https://github.com/canonical/operator/pull/2219). Charmcraft currently
uses `charm_spec` in the `init-extensions` tests, so this PR
preemptively modernises the test to use `State.from_context`, avoiding
the need to access `Context.charm_spec`.

The `init-extensions` tests run only in the Ubuntu 22.04 spread tests.
While that job is currently failing, the failing tests do not appear to
be the `init-extensions` tests:

```
2025-12-12 04:44:41 Successful tasks: 50
error: unsuccessful run
2025-12-12 04:44:41 Aborted tasks: 0
2025-12-12 04:44:41 Failed tasks: 3
    - google:ubuntu-22.04-64:tests/spread/smoketests/different-dir
    - google:ubuntu-22.04-64:tests/spread/smoketests/multi-base:basic
    - google:ubuntu-22.04-64:tests/spread/smoketests/multi-base:one_platform
2025-12-12 04:44:41 Failed task restore: 2
    - google:ubuntu-22.04-64:tests/spread/smoketests/multi-base:basic
    - google:ubuntu-22.04-64:tests/spread/smoketests/multi-base:one_platform
```

<details>
<summary>AFAICT the init-extensions tests pass, here's some relevant
output from <a
href=https://github.com/canonical/charmcraft/actions/runs/20154524656/job/57855410223?pr=2527>this
run</a>.</summary>

```
2025-12-12 03:40:14 Restoring google:ubuntu-22.04-64:tests/spread/commands/init-extensions:springboot (dec120311-758761)...
2025-12-12 03:40:28 Preparing google:ubuntu-22.04-64:tests/spread/smoketests/reactive:stable (dec120311-758761)...
2025-12-12 03:40:29 Executing google:ubuntu-22.04-64:tests/spread/smoketests/reactive:stable (dec120311-758761) (7/53)...
2025-12-12 03:40:34 Restoring google:ubuntu-22.04-64:tests/spread/commands/init-extensions:flask (dec120311-758749)...
2025-12-12 03:40:50 Preparing google:ubuntu-22.04-64:tests/spread/smoketests/reactive:two (dec120311-758749)...
2025-12-12 03:40:51 Executing google:ubuntu-22.04-64:tests/spread/smoketests/reactive:two (dec120311-758749) (8/53)...
2025-12-12 03:41:14 Restoring google:ubuntu-22.04-64:tests/spread/commands/init-extensions:expressjs (dec120311-758638)...
2025-12-12 03:41:14 Restoring google:ubuntu-22.04-64:tests/spread/commands/init-extensions:fastapi (dec120311-758711)...
2025-12-12 03:41:30 Preparing google:ubuntu-22.04-64:tests/spread/dependencies/ (dec120311-758711)...
2025-12-12 03:41:30 Preparing google:ubuntu-22.04-64:tests/spread/dependencies/ (dec120311-758638)...
2025-12-12 03:41:34 Restoring google:ubuntu-22.04-64:tests/spread/commands/init-extensions:go (dec120311-758738)...
2025-12-12 03:41:52 Preparing google:ubuntu-22.04-64:tests/spread/smoketests/multi-base:all (dec120311-758738)...
2025-12-12 03:41:55 Executing google:ubuntu-22.04-64:tests/spread/smoketests/multi-base:all (dec120311-758738) (9/53)...
2025-12-12 03:42:40 Restoring google:ubuntu-22.04-64:tests/spread/commands/init-extensions:django (dec120311-758757)...
```
</details>

<!-- Describe your changes -->
---

- [x] I've followed the [contribution
guidelines](https://github.com/canonical/charmcraft/blob/main/CONTRIBUTING.md).
- [x] I've signed the [CLA](http://www.ubuntu.com/legal/contributors/).
- [x] I've successfully run `make lint && make test`.
- [x] ~I've added or updated any relevant documentation.~ (N/A)
- [x] ~I've updated the relevant release notes.~ (N/A)